name: Execute remote shell script

on:
  workflow_run:
    workflows:
      - "Build Frontend and Push Docker Image"
      - "Build Backend and Push Docker Image"
    types:
      - completed

jobs:
  execute_remote_script:
    runs-on: ubuntu-latest
    env:
      WORKFLOW_COUNT: 0
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update workflow count
      run: |
        if [ "${{ github.event.workflow_run.name }}" == "Build Frontend and Push Docker Image" ]; then
          echo "WORKFLOW_COUNT=$(echo ${{ env.WORKFLOW_COUNT }} + 1 | bc)" >> $GITHUB_ENV
        elif [ "${{ github.event.workflow_run.name }}" == "Build Backend and Push Docker Image" ]; then
          echo "WORKFLOW_COUNT=$(echo ${{ env.WORKFLOW_COUNT }} + 1 | bc)" >> $GITHUB_ENV
        fi
        echo "Updated workflow count: ${{ env.WORKFLOW_COUNT }}"

    - name: Execute shell script on remote server
      if: ${{ env.WORKFLOW_COUNT >= 1 }}
      env:
        PRIVATE_KEY: ${{ secrets.REMOTE_SERVER_PRIVATE_KEY }}
        REMOTE_SERVER_USER: ${{ secrets.REMOTE_SERVER_USER }}
        REMOTE_SERVER_HOST: ${{ secrets.REMOTE_SERVER_HOST }}
        REMOTE_SCRIPT_PATH: ${{ secrets.REMOTE_SCRIPT_PATH }}
      run: |
        TEMP_DIR=$(mktemp -d)
        PRIVATE_KEY_FILE="$TEMP_DIR/private_key"
        echo "$PRIVATE_KEY" > "$PRIVATE_KEY_FILE"
        chmod 600 "$PRIVATE_KEY_FILE"
        ssh -i "$PRIVATE_KEY_FILE" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $REMOTE_SERVER_USER@$REMOTE_SERVER_HOST "bash -s" < $REMOTE_SCRIPT_PATH
